# This is the configuration for your Vite frontend site
[build]
  command = "npm run build"
  publish = "dist/spa" # Or "dist" if you changed it

# This rule is important for single-page applications like React
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200